language: python

jobs:
  include:
    - arch: arm64
      services: docker
      env:
        - CIBW_MANYLINUX_X86_64_IMAGE="quay.io/pypa/manylinux2014_aarch64"

env:
  global:
    - TWINE_USERNAME=__token__
    # Note: TWINE_PASSWORD is set to an API token in Travis settings

install:
  - sudo python3 -m pip install twine cibuildwheel==1.1.0

script:
  # build the wheels, put them into './wheelhouse'
  - sudo python3 -m cibuildwheel --output-dir wheelhouse

after_success:
  # if the release was tagged, upload them to PyPI
  - if [[ $TRAVIS_TAG ]]; then python -m twine upload wheelhouse/*.whl; fi
