environment:
  TWINE_USERNAME: __token__
  # Note: TWINE_PASSWORD is set to an API token in Appveyor settings

build_script:
  - pip install cibuildwheel==1.0.0
  - cibuildwheel --output-dir wheelhouse
  - >
    IF "%APPVEYOR_REPO_TAG%" == "true"
    (
    python3 -m pip install twine
    &&
    python3 -m twine upload wheelhouse/*.whl
    )
artifacts:
  - path: "wheelhouse\\*.whl"
    name: Wheels

